using System;
using System.Collections.Generic;

namespace SubnauticaRuntimeEditor.Core.MaterialEditor
{
	public static class MaterialEditorPropertyTypes
	{
		public static Dictionary<MaterialEditorProperties, PropertyType> TYPES = new Dictionary<MaterialEditorProperties, PropertyType>
		{
			{ MaterialEditorProperties.Color, new PropertyTypeColor("_Color", true) },
			{ MaterialEditorProperties.Mode, new PropertyTypeFloat("_Mode", 0.0f, 100f) },
			{ MaterialEditorProperties.SrcBlend, new PropertyTypeFloat("_SrcBlend", 0.0f, 100f) },
			{ MaterialEditorProperties.DstBlend, new PropertyTypeFloat("_DstBlend", 0.0f, 100f) },
			{ MaterialEditorProperties.SrcBlend2, new PropertyTypeFloat("_SrcBlend2", 0.0f, 100f) },
			{ MaterialEditorProperties.DstBlend2, new PropertyTypeFloat("_DstBlend2", 0.0f, 100f) },
			{ MaterialEditorProperties.AddSrcBlend, new PropertyTypeFloat("_AddSrcBlend", 0.0f, 100f) },
			{ MaterialEditorProperties.AddDstBlend, new PropertyTypeFloat("_AddDstBlend", 0.0f, 100f) },
			{ MaterialEditorProperties.AddSrcBlend2, new PropertyTypeFloat("_AddSrcBlend2", 0.0f, 100f) },
			{ MaterialEditorProperties.AddDstBlend2, new PropertyTypeFloat("_AddDstBlend2", 0.0f, 100f) },
			{ MaterialEditorProperties.EnableMisc, new PropertyTypeFloat("_EnableMisc", true) },
			{ MaterialEditorProperties.MyCullVariable, new PropertyTypeFloat("_MyCullVariable", 0.0f, 100f) },
			{ MaterialEditorProperties.ZWrite, new PropertyTypeToggle("_ZWrite") },
			{ MaterialEditorProperties.ZOffset, new PropertyTypeFloat("_ZOffset", 0.0f, 100f) },
			{ MaterialEditorProperties.EnableCutOff, new PropertyTypeFloat("_EnableCutOff", true) },
			{ MaterialEditorProperties.Cutoff, new PropertyTypeFloat("_Cutoff", 0f, 1f) },
			{ MaterialEditorProperties.EnableDitherAlpha, new PropertyTypeFloat("_EnableDitherAlpha", true) },
			{ MaterialEditorProperties.EnableVrFadeOut, new PropertyTypeFloat("_EnableVrFadeOut", true) },
			{ MaterialEditorProperties.EnableLighting, new PropertyTypeFloat("_EnableLighting", true) },
			{ MaterialEditorProperties.IBLreductionAtNight, new PropertyTypeFloat("_IBLreductionAtNight", 0f, 1f) },
			{ MaterialEditorProperties.EnableSimpleGlass, new PropertyTypeFloat("_EnableSimpleGlass", true) },
			{ MaterialEditorProperties.EnableVertexColor, new PropertyTypeFloat("_EnableVertexColor", true) },
			{ MaterialEditorProperties.EnableSchoolFish, new PropertyTypeFloat("_EnableSchoolFish", true) },
			{ MaterialEditorProperties.EnableMainMaps, new PropertyTypeFloat("_EnableMainMaps", true) },
			{ MaterialEditorProperties.MarmoSpecEnum, new PropertyTypeFloat("_MarmoSpecEnum", 0.0f, 100f) },
			{ MaterialEditorProperties.SpecColor, new PropertyTypeColor("_SpecColor", true) },
			{ MaterialEditorProperties.SpecInt, new PropertyTypeFloat("_SpecInt", 0.0f, 100f) },
			{ MaterialEditorProperties.Shininess, new PropertyTypeFloat("_Shininess", 2f, 8f) },
			{ MaterialEditorProperties.Fresnel, new PropertyTypeFloat("_Fresnel", 0f, 1f) },
			{ MaterialEditorProperties.EnableGlow, new PropertyTypeFloat("_EnableGlow", true) },
			{ MaterialEditorProperties.GlowColor, new PropertyTypeColor("_GlowColor", true) },
			{ MaterialEditorProperties.GlowUVfromVC, new PropertyTypeFloat("_GlowUVfromVC", 0.0f, 100f) },
			{ MaterialEditorProperties.GlowStrength, new PropertyTypeFloat("_GlowStrength", 0.0f, 100f) },
			{ MaterialEditorProperties.GlowStrengthNight, new PropertyTypeFloat("_GlowStrengthNight", 0.0f, 100f) },
			{ MaterialEditorProperties.EmissionLM, new PropertyTypeFloat("_EmissionLM", 0.0f, 100f) },
			{ MaterialEditorProperties.EmissionLMNight, new PropertyTypeFloat("_EmissionLMNight", 0.0f, 100f) },
			{ MaterialEditorProperties.EnableDetailMaps, new PropertyTypeFloat("_EnableDetailMaps", true) },
			{ MaterialEditorProperties.DetailIntensities, new PropertyTypeVector4("_DetailIntensities") },
			{ MaterialEditorProperties.EnableLightmap, new PropertyTypeFloat("_EnableLightmap", true) },
			{ MaterialEditorProperties.LightmapStrength, new PropertyTypeFloat("_LightmapStrength", 0.0f, 100f) },
			{ MaterialEditorProperties.Enable3Color, new PropertyTypeFloat("_Enable3Color", true) },
			{ MaterialEditorProperties.Color2, new PropertyTypeColor("_Color2", true) },
			{ MaterialEditorProperties.Color3, new PropertyTypeColor("_Color3", true) },
			{ MaterialEditorProperties.SpecColor2, new PropertyTypeColor("_SpecColor2", true) },
			{ MaterialEditorProperties.SpecColor3, new PropertyTypeColor("_SpecColor3", true) },
			{ MaterialEditorProperties.FX, new PropertyTypeFloat("FX", true) },
			{ MaterialEditorProperties.DeformParams, new PropertyTypeVector4("_DeformParams") },
			{ MaterialEditorProperties.FillSack, new PropertyTypeFloat("_FillSack", 0f, 1f) },
			{ MaterialEditorProperties.OverlayStrength, new PropertyTypeFloat("_OverlayStrength", 0f, 1f) },
			{ MaterialEditorProperties.GlowScrollColor, new PropertyTypeColor("_GlowScrollColor", true) },
			{ MaterialEditorProperties.Hypnotize, new PropertyTypeFloat("_Hypnotize", 0f, 1f) },
			{ MaterialEditorProperties.ScrollColor, new PropertyTypeColor("_ScrollColor", true) },
			{ MaterialEditorProperties.ColorStrength, new PropertyTypeColor("_ColorStrength", true) },
			{ MaterialEditorProperties.GlowMaskSpeed, new PropertyTypeVector4("_GlowMaskSpeed") },
			{ MaterialEditorProperties.ScrollSpeed, new PropertyTypeVector4("_ScrollSpeed") },
			{ MaterialEditorProperties.DetailsColor, new PropertyTypeColor("_DetailsColor", true) },
			{ MaterialEditorProperties.SquaresColor, new PropertyTypeColor("_SquaresColor", true) },
			{ MaterialEditorProperties.SquaresTile, new PropertyTypeFloat("_SquaresTile", 0.0f, 100f) },
			{ MaterialEditorProperties.SquaresSpeed, new PropertyTypeFloat("_SquaresSpeed", 0.0f, 100f) },
			{ MaterialEditorProperties.SquaresIntensityPow, new PropertyTypeFloat("_SquaresIntensityPow", 0.0f, 100f) },
			{ MaterialEditorProperties.NoiseSpeed, new PropertyTypeVector4("_NoiseSpeed") },
			{ MaterialEditorProperties.FakeSSSparams, new PropertyTypeVector4("_FakeSSSparams") },
			{ MaterialEditorProperties.FakeSSSSpeed, new PropertyTypeVector4("_FakeSSSSpeed") },
			{ MaterialEditorProperties.BorderColor, new PropertyTypeColor("_BorderColor", true) },
			{ MaterialEditorProperties.Built, new PropertyTypeFloat("_Built", 0.0f, 100f) },
			{ MaterialEditorProperties.BuildParams, new PropertyTypeVector4("_BuildParams") },
			{ MaterialEditorProperties.BuildLinear, new PropertyTypeFloat("_BuildLinear", 0.0f, 100f) },
			{ MaterialEditorProperties.NoiseThickness, new PropertyTypeFloat("_NoiseThickness", 0.0f, 100f) },
			{ MaterialEditorProperties.NoiseStr, new PropertyTypeFloat("_NoiseStr", 0.0f, 100f) },
			{ MaterialEditorProperties.FX_Vertex, new PropertyTypeFloat("FX_Vertex", true) },
			{ MaterialEditorProperties.Scale, new PropertyTypeVector4("_Scale") },
			{ MaterialEditorProperties.Frequency, new PropertyTypeVector4("_Frequency") },
			{ MaterialEditorProperties.Speed, new PropertyTypeVector4("_Speed") },
			{ MaterialEditorProperties.ObjectUp, new PropertyTypeVector4("_ObjectUp") },
			{ MaterialEditorProperties.WaveUpMin, new PropertyTypeFloat("_WaveUpMin", 0.0f, 100f) },
			{ MaterialEditorProperties.Fallof, new PropertyTypeFloat("_Fallof", 0.0f, 100f) },
			{ MaterialEditorProperties.RopeGravity, new PropertyTypeFloat("_RopeGravity", 0.0f, 100f) },
			{ MaterialEditorProperties.minYpos, new PropertyTypeFloat("_minYpos", 0.0f, 100f) },
			{ MaterialEditorProperties.maxYpos, new PropertyTypeFloat("_maxYpos", 0.0f, 100f) },
			{ MaterialEditorProperties.EnableBurst, new PropertyTypeFloat("_EnableBurst", true) },
			{ MaterialEditorProperties.Displacement, new PropertyTypeFloat("_Displacement", 0f, 5f) },
			{ MaterialEditorProperties.BurstStrength, new PropertyTypeFloat("_BurstStrength", 0f, 1f) },
			{ MaterialEditorProperties.Range, new PropertyTypeVector4("_Range") },
			{ MaterialEditorProperties.ClipRange, new PropertyTypeFloat("_ClipRange", 0.0f, 100f) },
			{ MaterialEditorProperties.EnableInfection, new PropertyTypeFloat("_EnableInfection", true) },
			// { MaterialEditorProperties.EnablePlayerInfection, new PropertyTypeFloat("_EnablePlayerInfection", true) },
			{ MaterialEditorProperties.InfectionHeightStrength, new PropertyTypeFloat("_InfectionHeightStrength", 0.0f, 100f) },
			{ MaterialEditorProperties.InfectionScale, new PropertyTypeVector4("_InfectionScale") },
			{ MaterialEditorProperties.InfectionOffset, new PropertyTypeVector4("_InfectionOffset") },
			{ MaterialEditorProperties.InfectionSpeed, new PropertyTypeVector4("_InfectionSpeed") },
			{ MaterialEditorProperties.ColorStrengthAtNight, new PropertyTypeColor("_ColorStrengthAtNight", true) },
			{ MaterialEditorProperties.EmissUV, new PropertyTypeVector4("_EmissUV") },
			{ MaterialEditorProperties.Emiss2UV, new PropertyTypeVector4("_Emiss2UV") },
			{ MaterialEditorProperties.ScrollSpeed2, new PropertyTypeVector4("_ScrollSpeed2") },
			{ MaterialEditorProperties.FadeAmount, new PropertyTypeFloat("_FadeAmount", 0.0f, 100f) },
			{ MaterialEditorProperties.FresnelFade, new PropertyTypeFloat("_FresnelFade", 0.0f, 100f) },
			{ MaterialEditorProperties.FresnelPow, new PropertyTypeFloat("_FresnelPow", 0.0f, 100f) },
			{ MaterialEditorProperties.InvFade, new PropertyTypeFloat("_InvFade", 0.0f, 100f) },
			{ MaterialEditorProperties.EmissiveStrengh, new PropertyTypeFloat("_EmissiveStrengh", 0.0f, 100f) },
			{ MaterialEditorProperties.scrollSpeed, new PropertyTypeVector4("_scrollSpeed") },
			{ MaterialEditorProperties.distortScrollSpeed, new PropertyTypeVector4("_distortScrollSpeed") },
			{ MaterialEditorProperties.distortStr, new PropertyTypeFloat("_distortStr", 0.0f, 100f) },
			{ MaterialEditorProperties.ClipOffset, new PropertyTypeFloat("_ClipOffset", 0.0f, 100f) },
			{ MaterialEditorProperties.ClipFade, new PropertyTypeFloat("_ClipFade", 0.0f, 100f) },
			{ MaterialEditorProperties.RimPower, new PropertyTypeFloat("_RimPower", 0.0f, 100f) },
			{ MaterialEditorProperties.IslandClouds, new PropertyTypeFloat("_IslandClouds", 0.0f, 100f) },
			{ MaterialEditorProperties.DomeClouds, new PropertyTypeFloat("_DomeClouds", 0.0f, 100f) },
			{ MaterialEditorProperties.PlanetClouds, new PropertyTypeFloat("_PlanetClouds", 0.0f, 100f) },
			{ MaterialEditorProperties.LightAmount, new PropertyTypeFloat("_LightAmount", 0.0f, 100f) },
			{ MaterialEditorProperties.StepSize, new PropertyTypeFloat("_StepSize", 0.0f, 100f) },
			{ MaterialEditorProperties.CloudsScatteringExponent, new PropertyTypeFloat("_CloudsScatteringExponent", 0.0f, 100f) },
			{ MaterialEditorProperties.CloudsScatteringMultiplier, new PropertyTypeFloat("_CloudsScatteringMultiplier", 0.0f, 100f) },
			{ MaterialEditorProperties.CloudsAttenuation, new PropertyTypeFloat("_CloudsAttenuation", 0.0f, 100f) },
			{ MaterialEditorProperties.SkyColorMultiplier, new PropertyTypeFloat("_SkyColorMultiplier", 0.0f, 100f) },
			{ MaterialEditorProperties.SunColorMultiplier, new PropertyTypeFloat("_SunColorMultiplier", 0.0f, 100f) },
			{ MaterialEditorProperties.ChannelLerp, new PropertyTypeVector4("_ChannelLerp") },
			{ MaterialEditorProperties.ChannelLerp2, new PropertyTypeVector4("_ChannelLerp2") },
			{ MaterialEditorProperties.LightMin, new PropertyTypeFloat("_LightMin", 0.0f, 100f) },
			{ MaterialEditorProperties.LightMul, new PropertyTypeFloat("_LightMul", 0.0f, 100f) },
			{ MaterialEditorProperties.HorizonFallof, new PropertyTypeFloat("_HorizonFallof", 0.0f, 100f) },
			{ MaterialEditorProperties.FadeInSkyColor, new PropertyTypeFloat("_FadeInSkyColor", 0.0f, 100f) },
			{ MaterialEditorProperties.AlphaPow, new PropertyTypeFloat("_AlphaPow", 0.0f, 100f) },
			{ MaterialEditorProperties.DeformStrength, new PropertyTypeVector4("_DeformStrength") },
			{ MaterialEditorProperties.DeformSpeed, new PropertyTypeVector4("_DeformSpeed") },
			{ MaterialEditorProperties.MixStrength, new PropertyTypeVector4("_MixStrength") },
			{ MaterialEditorProperties.MixSpeed, new PropertyTypeVector4("_MixSpeed") },
			{ MaterialEditorProperties.SurfFade, new PropertyTypeFloat("_SurfFade", 0.0f, 100f) },
			{ MaterialEditorProperties.SeaLevel, new PropertyTypeFloat("_SeaLevel", 0.0f, 100f) },
			{ MaterialEditorProperties.GridThickness, new PropertyTypeFloat("_GridThickness", 0.0f, 100f) },
			{ MaterialEditorProperties.GridSpacing, new PropertyTypeFloat("_GridSpacing", 0.0f, 100f) },
			{ MaterialEditorProperties.Tint, new PropertyTypeVector4("_Tint") },
			{ MaterialEditorProperties.FlowSpeed, new PropertyTypeFloat("_FlowSpeed", 0.0f, 100f) },
			{ MaterialEditorProperties.EmissiveCut, new PropertyTypeFloat("_EmissiveCut", 0.01f, 0.99f) },
			{ MaterialEditorProperties.Emission, new PropertyTypeFloat("_Emission", 0f, 1f) },
			{ MaterialEditorProperties.TintColor, new PropertyTypeColor("_TintColor", true) },
			{ MaterialEditorProperties.LiquidColor, new PropertyTypeColor("_LiquidColor", true) },
			{ MaterialEditorProperties.BubblesColor, new PropertyTypeColor("_BubblesColor", true) },
			{ MaterialEditorProperties.LiquidGlow, new PropertyTypeFloat("_LiquidGlow", 0.0f, 100f) },
			{ MaterialEditorProperties.BubblesGlow, new PropertyTypeFloat("_BubblesGlow", 0.0f, 100f) },
			{ MaterialEditorProperties.levelOffset, new PropertyTypeFloat("_levelOffset", 0.0f, 100f) },
			{ MaterialEditorProperties.BlurStrength, new PropertyTypeFloat("_BlurStrength", 0.0f, 100f) },
			{ MaterialEditorProperties.BlurWidth, new PropertyTypeFloat("_BlurWidth", 0.0f, 100f) },
			{ MaterialEditorProperties.rainAmount, new PropertyTypeFloat("_rainAmount", 0.0f, 100f) },
			{ MaterialEditorProperties.SurfLevel, new PropertyTypeFloat("_SurfLevel", 0.0f, 100f) },
			{ MaterialEditorProperties.TimeScale, new PropertyTypeFloat("_TimeScale", 0.0f, 100f) },
			{ MaterialEditorProperties.snowAmount, new PropertyTypeFloat("_snowAmount", 0.0f, 100f) },
			{ MaterialEditorProperties.BoxMin, new PropertyTypeVector4("_BoxMin") },
			{ MaterialEditorProperties.BoxMax, new PropertyTypeVector4("_BoxMax") },
			{ MaterialEditorProperties.Visibility, new PropertyTypeFloat("_Visibility", 0.0f, 100f) },
			{ MaterialEditorProperties.BIsForwardLighting, new PropertyTypeFloat("_BIsForwardLighting", 0.0f, 100f) },
			{ MaterialEditorProperties.LocalFloodLevel, new PropertyTypeFloat("_LocalFloodLevel", 0.0f, 100f) },
			{ MaterialEditorProperties.AffectedBySkyExposure, new PropertyTypeFloat("_AffectedBySkyExposure", 0.0f, 100f) },
			{ MaterialEditorProperties.SelfIllumination, new PropertyTypeFloat("_SelfIllumination", 0f, 1f) },
			{ MaterialEditorProperties.CylRadius, new PropertyTypeFloat("_CylRadius", 0.0f, 100f) },
			{ MaterialEditorProperties.MinY, new PropertyTypeFloat("_MinY", 0.0f, 100f) },
			{ MaterialEditorProperties.MaxY, new PropertyTypeFloat("_MaxY", 0.0f, 100f) },
			{ MaterialEditorProperties.PingColor, new PropertyTypeColor("_PingColor", true) },
			{ MaterialEditorProperties.PingCenter, new PropertyTypeVector4("_PingCenter") },
			{ MaterialEditorProperties.PingFrequency, new PropertyTypeFloat("_PingFrequency", 0.0f, 100f) },
			{ MaterialEditorProperties.DitherIntensity, new PropertyTypeFloat("_DitherIntensity", 0f, 1f) },
			{ MaterialEditorProperties.RadiusSqr, new PropertyTypeFloat("_RadiusSqr", 0.0f, 100f) },
			{ MaterialEditorProperties.NoiseScale, new PropertyTypeVector4("_NoiseScale") },
			{ MaterialEditorProperties.NoiseOffset, new PropertyTypeVector4("_NoiseOffset") },
			{ MaterialEditorProperties.Octaves, new PropertyTypeFloat("_Octaves", 0.0f, 100f) },
			{ MaterialEditorProperties.ClipedValue, new PropertyTypeFloat("_ClipedValue", 0.0f, 100f) },
			{ MaterialEditorProperties.MaskPow, new PropertyTypeFloat("_MaskPow", 0.0f, 100f) },
			{ MaterialEditorProperties.ClipMultiplier, new PropertyTypeFloat("_ClipMultiplier", 0.0f, 100f) },
			{ MaterialEditorProperties.TexScale, new PropertyTypeVector4("_TexScale") },
			{ MaterialEditorProperties.Dir, new PropertyTypeFloat("_Dir", 0f, 1f) },
			{ MaterialEditorProperties.Cycle, new PropertyTypeFloat("_Cycle", 0.0f, 100f) },
			{ MaterialEditorProperties.MainFoam, new PropertyTypeFloat("_MainFoam", 0.0f, 100f) },
			{ MaterialEditorProperties.TopFoamHeight, new PropertyTypeFloat("_TopFoamHeight", 0.0f, 100f) },
			{ MaterialEditorProperties.TopFoamHeightOffset, new PropertyTypeFloat("_TopFoamHeightOffset", 0.0f, 100f) },
			{ MaterialEditorProperties.FoamStrength, new PropertyTypeFloat("_FoamStrength", 0.0f, 100f) },
			{ MaterialEditorProperties.BorderFoam, new PropertyTypeFloat("_BorderFoam", 0.0f, 100f) },
			{ MaterialEditorProperties.BorderFoamStrength, new PropertyTypeFloat("_BorderFoamStrength", 0.0f, 100f) },
			{ MaterialEditorProperties.RefractStrength, new PropertyTypeFloat("_RefractStrength", 0.0f, 100f) },
			{ MaterialEditorProperties.LightingMultiplier, new PropertyTypeFloat("_LightingMultiplier", 0.0f, 100f) },
			{ MaterialEditorProperties.LightWrapAround, new PropertyTypeFloat("_LightWrapAround", 0f, 1f) },
			{ MaterialEditorProperties.NormalSharpness, new PropertyTypeFloat("_NormalSharpness", 0f, 1f) },
			{ MaterialEditorProperties.LightDesaturation, new PropertyTypeFloat("_LightDesaturation", 0f, 1f) },
			{ MaterialEditorProperties.EdgeThresholdMin, new PropertyTypeFloat("_EdgeThresholdMin", 0.0f, 100f) },
			{ MaterialEditorProperties.EdgeThreshold, new PropertyTypeFloat("_EdgeThreshold", 0.0f, 100f) },
			{ MaterialEditorProperties.EdgeSharpness, new PropertyTypeFloat("_EdgeSharpness", 0.0f, 100f) },
			{ MaterialEditorProperties.Value, new PropertyTypeFloat("_Value", 0.0f, 100f) },
			{ MaterialEditorProperties.Width, new PropertyTypeFloat("_Width", 0.0f, 100f) },
			{ MaterialEditorProperties.EdgeWidth, new PropertyTypeFloat("_EdgeWidth", 0.0f, 100f) },
			{ MaterialEditorProperties.BorderWidth, new PropertyTypeFloat("_BorderWidth", 0.0f, 100f) },
			{ MaterialEditorProperties.Overlay1_ST, new PropertyTypeVector4("_Overlay1_ST") },
			{ MaterialEditorProperties.Overlay2_ST, new PropertyTypeVector4("_Overlay2_ST") },
			{ MaterialEditorProperties.OverlayShift, new PropertyTypeVector4("_OverlayShift") },
			{ MaterialEditorProperties.OverlayAlpha, new PropertyTypeVector4("_OverlayAlpha") },
			{ MaterialEditorProperties.StencilComp, new PropertyTypeFloat("_StencilComp", 0.0f, 100f) },
			{ MaterialEditorProperties.Stencil, new PropertyTypeFloat("_Stencil", 0.0f, 100f) },
			{ MaterialEditorProperties.StencilOp, new PropertyTypeFloat("_StencilOp", 0.0f, 100f) },
			{ MaterialEditorProperties.StencilWriteMask, new PropertyTypeFloat("_StencilWriteMask", 0.0f, 100f) },
			{ MaterialEditorProperties.StencilReadMask, new PropertyTypeFloat("_StencilReadMask", 0.0f, 100f) },
			{ MaterialEditorProperties.ColorMask, new PropertyTypeFloat("_ColorMask", 0.0f, 100f) },
			{ MaterialEditorProperties.EnableSIG, new PropertyTypeFloat("_EnableSIG", true) },
			{ MaterialEditorProperties.CapBorderBlendRange, new PropertyTypeFloat("_CapBorderBlendRange", 0f, 1f) },
			{ MaterialEditorProperties.CapBorderBlendOffset, new PropertyTypeFloat("_CapBorderBlendOffset", -1f, 0f) },
			{ MaterialEditorProperties.CapBorderBlendAngle, new PropertyTypeFloat("_CapBorderBlendAngle", 0.5f, 5f) },
			{ MaterialEditorProperties.Amount, new PropertyTypeFloat("_Amount", 0.0f, 100f) },
			{ MaterialEditorProperties.ColorCenter, new PropertyTypeColor("_ColorCenter", true) },
			{ MaterialEditorProperties.ColorOuter, new PropertyTypeColor("_ColorOuter", true) },
			{ MaterialEditorProperties.MainScrollSpeed, new PropertyTypeVector4("_MainScrollSpeed") },
			{ MaterialEditorProperties.DetailScrollSpeed, new PropertyTypeVector4("_DetailScrollSpeed") },
			{ MaterialEditorProperties.NervesScrollSpeed, new PropertyTypeVector4("_NervesScrollSpeed") },
			{ MaterialEditorProperties.RefractScrollSpeed, new PropertyTypeVector4("_RefractScrollSpeed") },
			{ MaterialEditorProperties.FlowIntensity, new PropertyTypeFloat("_FlowIntensity", 0.0f, 100f) },
			{ MaterialEditorProperties.ColorCycleSpeed, new PropertyTypeColor("_ColorCycleSpeed", true) },
			{ MaterialEditorProperties.AlphaScale, new PropertyTypeFloat("_AlphaScale", 0.0f, 100f) },
			{ MaterialEditorProperties.SIGstr, new PropertyTypeVector4("_SIGstr") },
			{ MaterialEditorProperties.ObjectRight, new PropertyTypeVector4("_ObjectRight") },
			{ MaterialEditorProperties.WorldWaveDir, new PropertyTypeVector4("_WorldWaveDir") },
			{ MaterialEditorProperties.WaveAmount, new PropertyTypeFloat("_WaveAmount", 0.0f, 100f) },
			{ MaterialEditorProperties.WaveSpeed, new PropertyTypeFloat("_WaveSpeed", 0f, 1f) },
			{ MaterialEditorProperties.TimeOffset, new PropertyTypeFloat("_TimeOffset", 0.0f, 100f) },
			{ MaterialEditorProperties.BotColor, new PropertyTypeColor("_BotColor", true) },
			{ MaterialEditorProperties.BotColor2, new PropertyTypeColor("_BotColor2", true) },
			{ MaterialEditorProperties.GradientParams, new PropertyTypeVector4("_GradientParams") },
			{ MaterialEditorProperties.MaskScale, new PropertyTypeFloat("_MaskScale", 0.0f, 100f) },
			{ MaterialEditorProperties.MaskStr, new PropertyTypeFloat("_MaskStr", 0.0f, 100f) },
			{ MaterialEditorProperties.ForceNormals, new PropertyTypeFloat("_ForceNormals", 0f, 1f) },
			{ MaterialEditorProperties.CapColor, new PropertyTypeColor("_CapColor", true) },
			{ MaterialEditorProperties.CapSpecColor, new PropertyTypeColor("_CapSpecColor", true) },
			{ MaterialEditorProperties.CapEmissionScale, new PropertyTypeFloat("_CapEmissionScale", 0f, 2f) },
			{ MaterialEditorProperties.SideEmissionScale, new PropertyTypeFloat("_SideEmissionScale", 0f, 2f) },
			{ MaterialEditorProperties.CapScale, new PropertyTypeFloat("_CapScale", 0.0f, 100f) },
			{ MaterialEditorProperties.SideScale, new PropertyTypeFloat("_SideScale", 0.0f, 100f) },
			{ MaterialEditorProperties.TriplanarBlendRange, new PropertyTypeFloat("_TriplanarBlendRange", 0.1f, 80f) },
			{ MaterialEditorProperties.InnerBorderBlendRange, new PropertyTypeFloat("_InnerBorderBlendRange", 0f, 1f) },
			{ MaterialEditorProperties.InnerBorderBlendOffset, new PropertyTypeFloat("_InnerBorderBlendOffset", 0f, 1f) },
			{ MaterialEditorProperties.Gloss, new PropertyTypeFloat("_Gloss", 0f, 1f) },
			{ MaterialEditorProperties.EmissionScale, new PropertyTypeFloat("_EmissionScale", 0f, 2f) },
			{ MaterialEditorProperties.FaceUVSpeedX, new PropertyTypeFloat("_FaceUVSpeedX", -5f, 5f) },
			{ MaterialEditorProperties.FaceUVSpeedY, new PropertyTypeFloat("_FaceUVSpeedY", -5f, 5f) },
			{ MaterialEditorProperties.FaceColor, new PropertyTypeColor("_FaceColor", true) },
			{ MaterialEditorProperties.FaceDilate, new PropertyTypeFloat("_FaceDilate", -1f, 1f) },
			{ MaterialEditorProperties.OutlineColor, new PropertyTypeColor("_OutlineColor", true) },
			{ MaterialEditorProperties.OutlineUVSpeedX, new PropertyTypeFloat("_OutlineUVSpeedX", -5f, 5f) },
			{ MaterialEditorProperties.OutlineUVSpeedY, new PropertyTypeFloat("_OutlineUVSpeedY", -5f, 5f) },
			{ MaterialEditorProperties.OutlineWidth, new PropertyTypeFloat("_OutlineWidth", 0f, 1f) },
			{ MaterialEditorProperties.OutlineSoftness, new PropertyTypeFloat("_OutlineSoftness", 0f, 1f) },
			{ MaterialEditorProperties.Bevel, new PropertyTypeFloat("_Bevel", 0f, 1f) },
			{ MaterialEditorProperties.BevelOffset, new PropertyTypeFloat("_BevelOffset", -0.5f, 0.5f) },
			{ MaterialEditorProperties.BevelWidth, new PropertyTypeFloat("_BevelWidth", -0.5f, 0.5f) },
			{ MaterialEditorProperties.BevelClamp, new PropertyTypeFloat("_BevelClamp", 0f, 1f) },
			{ MaterialEditorProperties.BevelRoundness, new PropertyTypeFloat("_BevelRoundness", 0f, 1f) },
			{ MaterialEditorProperties.LightAngle, new PropertyTypeFloat("_LightAngle", 0f, 6.283185f) },
			{ MaterialEditorProperties.SpecularColor, new PropertyTypeColor("_SpecularColor", true) },
			{ MaterialEditorProperties.SpecularPower, new PropertyTypeFloat("_SpecularPower", 0f, 4f) },
			{ MaterialEditorProperties.Reflectivity, new PropertyTypeFloat("_Reflectivity", 5f, 15f) },
			{ MaterialEditorProperties.Diffuse, new PropertyTypeFloat("_Diffuse", 0f, 1f) },
			{ MaterialEditorProperties.Ambient, new PropertyTypeFloat("_Ambient", 1f, 0f) },
			{ MaterialEditorProperties.BumpOutline, new PropertyTypeFloat("_BumpOutline", 0f, 1f) },
			{ MaterialEditorProperties.BumpFace, new PropertyTypeFloat("_BumpFace", 0f, 1f) },
			{ MaterialEditorProperties.ReflectFaceColor, new PropertyTypeColor("_ReflectFaceColor", true) },
			{ MaterialEditorProperties.ReflectOutlineColor, new PropertyTypeColor("_ReflectOutlineColor", true) },
			{ MaterialEditorProperties.EnvMatrixRotation, new PropertyTypeVector4("_EnvMatrixRotation") },
			{ MaterialEditorProperties.UnderlayColor, new PropertyTypeColor("_UnderlayColor", true) },
			{ MaterialEditorProperties.UnderlayOffsetX, new PropertyTypeFloat("_UnderlayOffsetX", -1f, 1f) },
			{ MaterialEditorProperties.UnderlayOffsetY, new PropertyTypeFloat("_UnderlayOffsetY", -1f, 1f) },
			{ MaterialEditorProperties.UnderlayDilate, new PropertyTypeFloat("_UnderlayDilate", -1f, 1f) },
			{ MaterialEditorProperties.UnderlaySoftness, new PropertyTypeFloat("_UnderlaySoftness", 0f, 1f) },
			{ MaterialEditorProperties.GlowOffset, new PropertyTypeFloat("_GlowOffset", -1f, 1f) },
			{ MaterialEditorProperties.GlowInner, new PropertyTypeFloat("_GlowInner", 0f, 1f) },
			{ MaterialEditorProperties.GlowOuter, new PropertyTypeFloat("_GlowOuter", 0f, 1f) },
			{ MaterialEditorProperties.GlowPower, new PropertyTypeFloat("_GlowPower", 1f, 0f) },
			{ MaterialEditorProperties.WeightNormal, new PropertyTypeFloat("_WeightNormal", 0.0f, 100f) },
			{ MaterialEditorProperties.WeightBold, new PropertyTypeFloat("_WeightBold", 0.0f, 100f) },
			{ MaterialEditorProperties.ShaderFlags, new PropertyTypeFloat("_ShaderFlags", 0.0f, 100f) },
			{ MaterialEditorProperties.ScaleRatioA, new PropertyTypeFloat("_ScaleRatioA", 0.0f, 100f) },
			{ MaterialEditorProperties.ScaleRatioB, new PropertyTypeFloat("_ScaleRatioB", 0.0f, 100f) },
			{ MaterialEditorProperties.ScaleRatioC, new PropertyTypeFloat("_ScaleRatioC", 0.0f, 100f) },
			{ MaterialEditorProperties.TextureWidth, new PropertyTypeFloat("_TextureWidth", 0.0f, 100f) },
			{ MaterialEditorProperties.TextureHeight, new PropertyTypeFloat("_TextureHeight", 0.0f, 100f) },
			{ MaterialEditorProperties.GradientScale, new PropertyTypeFloat("_GradientScale", 0.0f, 100f) },
			{ MaterialEditorProperties.ScaleX, new PropertyTypeFloat("_ScaleX", 0.0f, 100f) },
			{ MaterialEditorProperties.ScaleY, new PropertyTypeFloat("_ScaleY", 0.0f, 100f) },
			{ MaterialEditorProperties.PerspectiveFilter, new PropertyTypeFloat("_PerspectiveFilter", 0f, 1f) },
			{ MaterialEditorProperties.Sharpness, new PropertyTypeFloat("_Sharpness", -1f, 1f) },
			{ MaterialEditorProperties.VertexOffsetX, new PropertyTypeFloat("_VertexOffsetX", 0.0f, 100f) },
			{ MaterialEditorProperties.VertexOffsetY, new PropertyTypeFloat("_VertexOffsetY", 0.0f, 100f) },
			{ MaterialEditorProperties.MaskCoord, new PropertyTypeVector4("_MaskCoord") },
			{ MaterialEditorProperties.ClipRect, new PropertyTypeVector4("_ClipRect") },
			{ MaterialEditorProperties.MaskSoftnessX, new PropertyTypeFloat("_MaskSoftnessX", 0.0f, 100f) },
			{ MaterialEditorProperties.MaskSoftnessY, new PropertyTypeFloat("_MaskSoftnessY", 0.0f, 100f) },
			{ MaterialEditorProperties.CullMode, new PropertyTypeFloat("_CullMode", 0.0f, 100f) },
			{ MaterialEditorProperties.DiffusePower, new PropertyTypeFloat("_DiffusePower", 1f, 4f) },
			{ MaterialEditorProperties.UseUIAlphaClip, new PropertyTypeToggle("_UseUIAlphaClip") },
			{ MaterialEditorProperties.Ztest, new PropertyTypeFloat("_Ztest", 0.0f, 100f) },
			{ MaterialEditorProperties.AffectedByDayNightCycle, new PropertyTypeFloat("_AffectedByDayNightCycle", 0.0f, 100f) },
			{ MaterialEditorProperties.FX_LightMode, new PropertyTypeFloat("FX_LightMode", 0.0f, 100f) },
			{ MaterialEditorProperties.NormalStrength, new PropertyTypeFloat("_NormalStrength", 0.0f, 100f) },
			{ MaterialEditorProperties.NormalMap_Speed, new PropertyTypeVector4("_NormalMap_Speed") },
			{ MaterialEditorProperties.NormalMap_TriplanarUV, new PropertyTypeVector4("_NormalMap_TriplanarUV") },
			{ MaterialEditorProperties.MainTex_Speed, new PropertyTypeVector4("_MainTex_Speed") },
			{ MaterialEditorProperties.MainTex_TriplanarUV, new PropertyTypeVector4("_MainTex_TriplanarUV") },
			{ MaterialEditorProperties.MainTex2_Speed, new PropertyTypeVector4("_MainTex2_Speed") },
			{ MaterialEditorProperties.MainTex2_TriplanarUV, new PropertyTypeVector4("_MainTex2_TriplanarUV") },
			{ MaterialEditorProperties.DeformMap_Speed, new PropertyTypeVector4("_DeformMap_Speed") },
			{ MaterialEditorProperties.DeformMap_TriplanarUV, new PropertyTypeVector4("_DeformMap_TriplanarUV") },
			{ MaterialEditorProperties.RefractMap_Speed, new PropertyTypeVector4("_RefractMap_Speed") },
			{ MaterialEditorProperties.RefractMap_TriplanarUV, new PropertyTypeVector4("_RefractMap_TriplanarUV") },
			{ MaterialEditorProperties.Angle, new PropertyTypeFloat("_Angle", 0.0f, 100f) },
			{ MaterialEditorProperties.AlphaFrom, new PropertyTypeFloat("_AlphaFrom", 0f, 1f) },
			{ MaterialEditorProperties.AlphaTo, new PropertyTypeFloat("_AlphaTo", 0f, 1f) },
			{ MaterialEditorProperties.OverlayIntensity, new PropertyTypeFloat("_OverlayIntensity", 0.0f, 100f) },
			{ MaterialEditorProperties.UseBackground, new PropertyTypeToggle("_UseBackground") },
			{ MaterialEditorProperties.TopBorder, new PropertyTypeFloat("_TopBorder", 0.0f, 100f) },
			{ MaterialEditorProperties.BottomBorder, new PropertyTypeFloat("_BottomBorder", 0.0f, 100f) },
			{ MaterialEditorProperties.Fill, new PropertyTypeFloat("_Fill", 0.0f, 100f) },
			{ MaterialEditorProperties.Subdivide, new PropertyTypeToggle("_Subdivide") },
			{ MaterialEditorProperties.Subdivisions, new PropertyTypeFloat("_Subdivisions", 0f, 20f) },
			{ MaterialEditorProperties.SeparatorWidth, new PropertyTypeFloat("_SeparatorWidth", 0.0f, 100f) },
			{ MaterialEditorProperties.SeparatorSmooth, new PropertyTypeFloat("_SeparatorSmooth", 0f, 0.999999f) },
			{ MaterialEditorProperties.Shear, new PropertyTypeToggle("_Shear") },
			{ MaterialEditorProperties.ShearTop, new PropertyTypeFloat("_ShearTop", 0.0f, 100f) },
			{ MaterialEditorProperties.ShearBottom, new PropertyTypeFloat("_ShearBottom", 0.0f, 100f) },
			{ MaterialEditorProperties.TileX, new PropertyTypeFloat("_TileX", 0.0f, 100f) },
			{ MaterialEditorProperties.TileY, new PropertyTypeFloat("_TileY", 0.0f, 100f) },
			{ MaterialEditorProperties.Size, new PropertyTypeFloat("_Size", 0.0f, 100f) },
			{ MaterialEditorProperties.SrcFactor, new PropertyTypeFloat("_SrcFactor", 0.0f, 100f) },
			{ MaterialEditorProperties.DstFactor, new PropertyTypeFloat("_DstFactor", 0.0f, 100f) },
			{ MaterialEditorProperties.Chroma, new PropertyTypeFloat("_Chroma", 0f, 1f) },
			{ MaterialEditorProperties.NotificationStrength, new PropertyTypeFloat("_NotificationStrength", 0.0f, 100f) },
			{ MaterialEditorProperties.FillRect, new PropertyTypeVector4("_FillRect") },
			{ MaterialEditorProperties.FillValue, new PropertyTypeFloat("_FillValue", 0.0f, 100f) },
			{ MaterialEditorProperties.Slice9Grid, new PropertyTypeToggle("_Slice9Grid") },
			{ MaterialEditorProperties.Radius, new PropertyTypeFloat("_Radius", 0.0f, 100f) },
			{ MaterialEditorProperties.Cut, new PropertyTypeFloat("_Cut", 0f, 1f) },
			{ MaterialEditorProperties.Antialias, new PropertyTypeFloat("_Antialias", 0.0f, 100f) },
			{ MaterialEditorProperties.Edge, new PropertyTypeFloat("_Edge", 0.0f, 100f) },
			{ MaterialEditorProperties.ColorBackground, new PropertyTypeColor("_ColorBackground", true) },
			{ MaterialEditorProperties.ColorEdge, new PropertyTypeColor("_ColorEdge", true) },
			{ MaterialEditorProperties.Value0, new PropertyTypeFloat("_Value0", 0.0f, 100f) },
			{ MaterialEditorProperties.Value1, new PropertyTypeFloat("_Value1", 0.0f, 100f) },
			{ MaterialEditorProperties.Value2, new PropertyTypeFloat("_Value2", 0.0f, 100f) },
			{ MaterialEditorProperties.Color0, new PropertyTypeColor("_Color0", true) },
			{ MaterialEditorProperties.Color1, new PropertyTypeColor("_Color1", true) },
			{ MaterialEditorProperties.SrcFactorA, new PropertyTypeFloat("_SrcFactorA", 0.0f, 100f) },
			{ MaterialEditorProperties.DstFactorA, new PropertyTypeFloat("_DstFactorA", 0.0f, 100f) },
			{ MaterialEditorProperties.AlphaPremultiply, new PropertyTypeToggle("_AlphaPremultiply") },
			{ MaterialEditorProperties.Cull, new PropertyTypeFloat("_Cull", 0.0f, 100f) },
			{ MaterialEditorProperties.RayDir, new PropertyTypeVector4("_RayDir") },
			{ MaterialEditorProperties.Length, new PropertyTypeFloat("_Length", 0.0f, 100f) },
			{ MaterialEditorProperties.DetailsOnly, new PropertyTypeFloat("_DetailsOnly", 0.0f, 100f) },
			{ MaterialEditorProperties.RimColor, new PropertyTypeColor("_RimColor", true) },
			{ MaterialEditorProperties.MainSpeed, new PropertyTypeVector4("_MainSpeed") },
			{ MaterialEditorProperties.MainOffset, new PropertyTypeFloat("_MainOffset", 0.0f, 100f) },
			{ MaterialEditorProperties.DetailsSpeed, new PropertyTypeVector4("_DetailsSpeed") },
			{ MaterialEditorProperties.DeformNormalStrength, new PropertyTypeFloat("_DeformNormalStrength", 0.0f, 100f) },
			{ MaterialEditorProperties.SinWaveFrequency, new PropertyTypeVector4("_SinWaveFrequency") },
			{ MaterialEditorProperties.SinWaveSpeed, new PropertyTypeVector4("_SinWaveSpeed") },
			{ MaterialEditorProperties.SinWaveStrength, new PropertyTypeVector4("_SinWaveStrength") },
			{ MaterialEditorProperties.SkyMultiplier, new PropertyTypeVector4("_SkyMultiplier") },
			{ MaterialEditorProperties.betaR, new PropertyTypeVector4("_betaR") },
			{ MaterialEditorProperties.betaM, new PropertyTypeVector4("_betaM") },
			{ MaterialEditorProperties.GroundColor, new PropertyTypeColor("_GroundColor", true) },
			{ MaterialEditorProperties.SunDir, new PropertyTypeVector4("_SunDir") },
			{ MaterialEditorProperties.NightHorizonColor, new PropertyTypeColor("_NightHorizonColor", true) },
			{ MaterialEditorProperties.NightZenithColor, new PropertyTypeColor("_NightZenithColor", true) },
			{ MaterialEditorProperties.MoonOuterCorona, new PropertyTypeVector4("_MoonOuterCorona") },
			{ MaterialEditorProperties.colorCorrection, new PropertyTypeColor("_colorCorrection", true) },
			{ MaterialEditorProperties.OuterSpaceIntensity, new PropertyTypeFloat("_OuterSpaceIntensity", 0f, 2f) },
			{ MaterialEditorProperties.OffsetHeight, new PropertyTypeFloat("_OffsetHeight", 0.06f, 0.4f) },
			{ MaterialEditorProperties.VertexStrength, new PropertyTypeFloat("_VertexStrength", 0.0f, 100f) },
			{ MaterialEditorProperties.RipplesAnimParams, new PropertyTypeVector4("_RipplesAnimParams") },
			{ MaterialEditorProperties.RippleParams, new PropertyTypeVector4("_RippleParams") },
			{ MaterialEditorProperties.RipplePos1, new PropertyTypeVector4("_RipplePos1") },
			{ MaterialEditorProperties.MovementDir, new PropertyTypeVector4("_MovementDir") },
			{ MaterialEditorProperties.Strech, new PropertyTypeFloat("_Strech", 0.0f, 100f) },
			{ MaterialEditorProperties.EnableFXMesmer, new PropertyTypeFloat("_EnableFXMesmer", true) },
			{ MaterialEditorProperties.sunSensitivity, new PropertyTypeFloat("_sunSensitivity", 0.0f, 100f) },
			{ MaterialEditorProperties.PixelSnap, new PropertyTypeFloat("PixelSnap", 0.0f, 100f) },
			{ MaterialEditorProperties.BorderTint, new PropertyTypeVector4("_BorderTint") },
			{ MaterialEditorProperties.BorderBlendRange, new PropertyTypeFloat("_BorderBlendRange", 0f, 1f) },
			{ MaterialEditorProperties.BorderBlendOffset, new PropertyTypeFloat("_BorderBlendOffset", 0f, 1f) },
			{ MaterialEditorProperties.BlendSrcFactor, new PropertyTypeFloat("_BlendSrcFactor", 0.0f, 100f) },
			{ MaterialEditorProperties.BlendDstFactor, new PropertyTypeFloat("_BlendDstFactor", 0.0f, 100f) },
			{ MaterialEditorProperties.IsOpaque, new PropertyTypeFloat("_IsOpaque", 0.0f, 100f) },
			{ MaterialEditorProperties.AlphaTestValue, new PropertyTypeFloat("_AlphaTestValue", 0.0f, 100f) },
			{ MaterialEditorProperties.TriplanarScale, new PropertyTypeFloat("_TriplanarScale", 0.0f, 100f) },
			{ MaterialEditorProperties.FlowAmount, new PropertyTypeFloat("_FlowAmount", 0.0f, 100f) },
			{ MaterialEditorProperties.MaskSpeed, new PropertyTypeFloat("_MaskSpeed", 0.0f, 100f) },
			{ MaterialEditorProperties.FlowScale, new PropertyTypeFloat("_FlowScale", 0.0f, 100f) },
			{ MaterialEditorProperties.AnimSpeed, new PropertyTypeFloat("_AnimSpeed", 0.0f, 100f) },
			{ MaterialEditorProperties.AnimStrength, new PropertyTypeFloat("_AnimStrength", 0f, 1f) },
			{ MaterialEditorProperties.Offset, new PropertyTypeFloat("_Offset", 0.0f, 100f) },
			{ MaterialEditorProperties.gravityStrength, new PropertyTypeFloat("_gravityStrength", 0.0f, 100f) },
			{ MaterialEditorProperties.SolidColor, new PropertyTypeColor("_SolidColor", true) },
			{ MaterialEditorProperties.Intensity, new PropertyTypeFloat("_Intensity", 0f, 1f) },
			{ MaterialEditorProperties.ImpactIntensity, new PropertyTypeFloat("_ImpactIntensity", 0f, 1f) },
			{ MaterialEditorProperties.ImpactPosition, new PropertyTypeVector4("_ImpactPosition") },
			{ MaterialEditorProperties.ImpactParams, new PropertyTypeVector4("_ImpactParams") },
			{ MaterialEditorProperties.EnabledSize, new PropertyTypeFloat("_EnabledSize", true) },
			{ MaterialEditorProperties.DisabledSize, new PropertyTypeFloat("_DisabledSize", 0.0f, 100f) },
			{ MaterialEditorProperties.WobbleParams, new PropertyTypeVector4("_WobbleParams") },
			{ MaterialEditorProperties.FragColor, new PropertyTypeColor("_FragColor", true) },
			{ MaterialEditorProperties.RefractUV, new PropertyTypeVector4("_RefractUV") },
			{ MaterialEditorProperties.RefractSpeed, new PropertyTypeVector4("_RefractSpeed") },
			{ MaterialEditorProperties.DeformUV, new PropertyTypeVector4("_DeformUV") },
			{ MaterialEditorProperties.FragsUV, new PropertyTypeVector4("_FragsUV") },
			{ MaterialEditorProperties.ScrollSpeed3, new PropertyTypeVector4("_ScrollSpeed3") },
			{ MaterialEditorProperties.DeformStrengthFrag, new PropertyTypeFloat("_DeformStrengthFrag", 0.0f, 100f) },
			{ MaterialEditorProperties.MinShadingSmoothness, new PropertyTypeFloat("_MinShadingSmoothness", 0.0f, 100f) },
			{ MaterialEditorProperties.MaxShadingSmoothness, new PropertyTypeFloat("_MaxShadingSmoothness", 0.0f, 100f) },
			{ MaterialEditorProperties.ScanIntensity, new PropertyTypeFloat("_ScanIntensity", 0.0f, 100f) },
			{ MaterialEditorProperties.ScanFrequency, new PropertyTypeFloat("_ScanFrequency", 0.0f, 100f) },
			{ MaterialEditorProperties.ScanSpeed, new PropertyTypeFloat("_ScanSpeed", 0.0f, 100f) },
			{ MaterialEditorProperties.ScanWidth, new PropertyTypeFloat("_ScanWidth", 0.0f, 100f) },
			{ MaterialEditorProperties.WireframeIntensity, new PropertyTypeFloat("_WireframeIntensity", 0.0f, 100f) },
			{ MaterialEditorProperties.WireframeDensity, new PropertyTypeFloat("_WireframeDensity", 0.0f, 100f) },
			{ MaterialEditorProperties.WireframeWidth, new PropertyTypeFloat("_WireframeWidth", 0.0f, 100f) },
			{ MaterialEditorProperties.FadeRadius, new PropertyTypeFloat("_FadeRadius", 0.0f, 100f) },
			{ MaterialEditorProperties.FadeSharpness, new PropertyTypeFloat("_FadeSharpness", 0.0f, 100f) },
			{ MaterialEditorProperties.NoiseIntensity, new PropertyTypeFloat("_NoiseIntensity", 0f, 1f) },
			{ MaterialEditorProperties.RadialFade, new PropertyTypeFloat("_RadialFade", 0.0f, 100f) },
			{ MaterialEditorProperties.DetailsColorStrength, new PropertyTypeColor("_DetailsColorStrength", true) },
			{ MaterialEditorProperties.RipplesFrequency, new PropertyTypeFloat("_RipplesFrequency", 0.0f, 100f) },
			{ MaterialEditorProperties.RipplesPow, new PropertyTypeFloat("_RipplesPow", 0.0f, 100f) },
			{ MaterialEditorProperties.RotationSpeed, new PropertyTypeFloat("_RotationSpeed", 0.0f, 100f) },
			{ MaterialEditorProperties.Glossiness, new PropertyTypeFloat("_Glossiness", 0f, 1f) },
			{ MaterialEditorProperties.GlossMapScale, new PropertyTypeFloat("_GlossMapScale", 0f, 1f) },
			{ MaterialEditorProperties.SmoothnessTextureChannel, new PropertyTypeFloat("_SmoothnessTextureChannel", 0.0f, 100f) },
			{ MaterialEditorProperties.Metallic, new PropertyTypeFloat("_Metallic", 0f, 1f) },
			{ MaterialEditorProperties.SpecularHighlights, new PropertyTypeToggle("_SpecularHighlights") },
			{ MaterialEditorProperties.GlossyReflections, new PropertyTypeToggle("_GlossyReflections") },
			{ MaterialEditorProperties.BumpScale, new PropertyTypeFloat("_BumpScale", 0.0f, 100f) },
			{ MaterialEditorProperties.Parallax, new PropertyTypeFloat("_Parallax", 0.005f, 0.08f) },
			{ MaterialEditorProperties.OcclusionStrength, new PropertyTypeFloat("_OcclusionStrength", 0f, 1f) },
			{ MaterialEditorProperties.EmissionColor, new PropertyTypeColor("_EmissionColor") },
			{ MaterialEditorProperties.DetailNormalMapScale, new PropertyTypeFloat("_DetailNormalMapScale", 0.0f, 100f) },
			{ MaterialEditorProperties.UVSec, new PropertyTypeFloat("_UVSec", 0.0f, 100f) },

		};
	}
}